spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true

server:
  port: ${APP_PORT:8080}
  error:
    include-message: false
    include-stacktrace: never

logging:
  level:
    root: INFO
    com.restaurant: INFO
  file:
    name: /var/log/restaurant/application.log
    max-size: 10MB
    max-history: 30
